--- #YAML:1.0
name:               SVG-Sparkline
version:            0.1.0
abstract:           Create Sparklines in SVG
author:
    - G. Wade Johnson <wade@anomaly.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:        0
    SVG:         2.49
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
